# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(0c0b0cee) rgba(e2dddcee)
    border_size = 2
    gaps_in = 3
    gaps_out = 4
}

group {
    col.border_active = rgba(e2dddcee)
    col.border_inactive = rgb(0c0b0c)

    groupbar {
        col.active = rgba(c38b7b99)
        col.inactive = rgba(584e5188)
        text_color = rgb(FAFCFB)
        text_color_inactive = rgba(FAFCFBee)
    }
}

decoration {
    rounding = 3
    rounding_power = 3
    blur {
        enabled = true
        size = 12
        passes = 4
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }
    shadow {
      enabled = yes
      render_power = 3
      range = 16
      color = rgba(00000052)
    }
}

windowrule = opacity 0.88 0.82, match:tag terminal
windowrule = opacity 0.94 0.88, match:class ^(Alacritty|kitty|foot)$
windowrule = opacity 0.78 0.73, match:class ^(nautilus|Nautilus)$


windowrule = match:class ^(vesktop|Vesktop)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(code|VSCode|VSCodium)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(chromium|Chromium|google-chrome|Brave|brave-browser)$, opacity 1.0 override, no_dim on